### ISSUE TITLE
Should PacketIn messages identify the source device_id of packets?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#278] opened 2020-03-29 08:51 UTC
I do not see a way that this is done in the current spec.  Should there be a way?

If so, it seems like a straightforward way would be to add a `device_id` field to the `PacketIn` message type.

Similarly, I do not see a way for a client to specify which device a `PacketOut` message should be sent to.  Should there be a way to specify that?

If so, then the simplest way would be to restrict each `PacketOut` message to go to a single device, and add a `device_id` field to the `PacketOut` message to specify it.

One could make that a repeated field if it was desired to send a single `PacketOut` message from client to server, but have the packet sent to multiple devices.

**Comment by antoninbas** [comment] 2020-03-29 19:53
Duplicate of #277

**Closed by antoninbas** 2020-03-29 19:53 UTC
