### ISSUE TITLE
Write multicast group error.

### ISSUE THREAD

**Issue by vilelamarcospaulo** [p4lang/p4runtime#72] opened 2018-10-18 19:51 UTC
Hi,
I'm having an issue when I try write a multicast group with p4runtime. The connection is OK and i can read/write counters and tables, but when I try write a multicast group I receive: **grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, )>**

the log of my controller is this:

connected with swith s1 on 127.0.0.1:50051
connected with swith s2 on 127.0.0.1:50052
connected with swith s3 on 127.0.0.1:50053

**sending write request:**

device_id: 2
election_id {
  low: 1
}
updates {
  type: INSERT
  entity {
    packet_replication_engine_entry {
      multicast_group_entry {
        multicast_group_id: 1
        replicas {
          egress_port: 1
          instance: 1
        }
        replicas {
          egress_port: 2
          instance: 1
        }
        replicas {
          egress_port: 3
          instance: 1
        }
      }
    }
  }
}

**Comment by antoninbas** [comment] 2018-10-19 16:44
This repo is for spec issues only. Please use the p4lang/PI or p4lang/behavioral-model repos next time, as they implement P4Runtime.
The `UNKNOWN` error code usually indicates that there was an error in the target as it was processing the required operations. Assuming you are using bmv2, you will need to look at the bmv2 logs to figure out what the issue is. If bmv2 crashed, a stack trace would be useful.

**Comment by antoninbas** [comment] 2018-10-19 18:12
I tried this message and I didn't get any issue, so you'll definitely need to take a look at the bmv2 logs.

**Comment by Luxzero** [comment] 2018-11-05 18:54
Hello. I'm having trouble writing a multicast group with p4runtime. Can you show me how to do it exactly? I can't find anything about it.

**Comment by antoninbas** [comment] 2018-11-05 19:05
https://s3-us-west-2.amazonaws.com/p4runtime/docs/master/P4Runtime-Spec.html#sec-multicastgroupentry
https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch_grpc/tests/test_pre.cpp

**Comment by antoninbas** [comment] 2018-11-07 18:02
Closing this. If you need further help, please send an email to the p4-dev mailing list or reach out to us on the p4.org slack channel.

**Closed by antoninbas** 2018-11-07 18:02 UTC
