### ISSUE TITLE
Remove "- Amazon S3" from P4Runtime Spec PDF

### ISSUE THREAD

**Issue by konne-google** [p4lang/p4runtime#197] opened 2019-04-19 16:35 UTC
Whenever I search for the P4Runtime spec, I get these results on Google with Amazon S3 on the title. Is it possible to remove that?

![image](https://user-images.githubusercontent.com/41303792/56433575-1e008100-6286-11e9-87f4-3231452ea089.png)

**Comment by konne-google** [comment] 2019-04-24 23:04
Are you the expert on this Andy?

**Comment by ccascone** [comment] 2019-04-24 23:11
I checked the PDF  and it seems there's no mention to "Amazon S3" in the PDF metadata, maybe Amazon appends " - Amazon S3" to every file publicly hosted on S3 and advertised to Googlebot? Possible solutions could be:
* Host automatic spec PDF builds somewhere else (e.g. Google Cloud)
* Change S3 preferences to NOT export PDF spec builds to Googlebot
* Hack things around / do some SEO to make sure the first result when googling for "p4runtime" is either https://p4.org/specs/ or this repo URL.

**Comment by jafingerhut** [comment] 2019-04-24 23:23
@konne-google I am most definitely not an expert on this stuff.  Carmelo sounds like he is at least ten steps ahead of me on thoughts of why this could be happening :)

**Comment by antoninbas** [comment] 2019-04-24 23:26
Whichever way we go, let's preserve the ability to visualize the rendered HTML & PDF documents for a PR before merging it.

**Comment by jnfoster** [comment] 2019-04-24 23:29
I believe the issue is that the P4 Runtime specification documents (HTML and PDF) are hosted on S3 rather than on GitHub pages, like the other specs. The P4 Runtime WG preferred it this way.

See here:
https://github.com/p4lang/p4lang.github.io/blob/master/_pages/specs.html

Perhaps we should make our processes more uniform and store the canonical versions for all P4 specifications in GitHub? We can still have the S3 as a mirror.

**Comment by jafingerhut** [comment] 2019-04-24 23:32
My home page is p4.org now.  I just click on the "Specifications" link and I am there.  What's the problem? :)

**Comment by ccascone** [comment] 2019-04-24 23:32
In this specific case (see screenshot above), that result is for the master build (i.e. working copy). Is there a way to automate the upload of working spec PDFs to GitHub pages?

Otherwise, regarding option 2, I'm not an expert on Amazon S3, but maybe there's an ACL rule to make files public but NOT indexed by search engines? https://github.com/p4lang/p4runtime/blob/master/.travis.yml#L24

**Comment by antoninbas** [comment] 2019-09-02 19:14
Let's see if something can be done about this before the P4Runtime v1.1.0 release.

**Comment by antoninbas** [comment] 2019-10-09 00:47
Started working on this for the v1.1.0 release. Here is the PoR:

 * latest (master) version and all tagged versions will be hosted on Github pages
 * the new official links (to-be-updated on p4.org) are:
    - https://p4.org/p4runtime/spec/v1.0.0/P4Runtime-Spec.html for v1.0.0 release
    - https://p4.org/p4runtime/spec/master/P4Runtime-Spec.html for current working version
 * the generated specs will still be uploaded to Amazon S3 (in particular for the sake of visualizing the rendered documents for each open PR), but the S3 bucket will no longer be indexable by search engines (using robots.txt file)

**Comment by antoninbas** [comment] 2019-11-29 01:24
I'm closing this. You can still see the "Amazon S3" link in the results but it is slowly getting dethroned by the Github link.

**Closed by antoninbas** 2019-11-29 01:24 UTC
