### ISSUE TITLE
Provide Bazel BUILD files for protos

### ISSUE THREAD

**Issue by bocon13** [p4lang/p4runtime#4] opened 2018-07-18 18:02 UTC
Add support for building protos with Bazel so that this repository can be included in other projects as a remote workspace.

**Comment by antoninbas** [comment] 2018-07-26 23:17
So actually, this is harder / more annoying than it looks. If I want to use a recent Bazel version (say 0.13), I cannot use the Protobuf & gRPC versions that I want to use (resp. 3.2.0 and 1.3.2) because that Protobuf version has a BUILD file that is no longer a correct Bazel BUILD file.

So if I don't see how I can satisfy all of these:
a) recent Bazel
b) older versions of Protobuf & gRPC
c) pre-defined rules (Bazel built-in `proto_library` or better yet these rules: https://github.com/pubref/rules_protobuf)

I could probably give up on c), but then I would need to invoke `protoc` manually (i.e. define my own rules) and that doesn't sound ideal.

@bocon13 do you have thoughts on this? Things seem to work with the latest Protobuf version, but that's not really what I'd like to use.

**Comment by bocon13** [comment] 2018-07-26 23:32
I've been looking into this, and there are some bugs/problems with native `proto_library` and `cc_proto_library` when used with the `proto_sources_root` attribute. The work around seems to be to use a `genrule` to remap the proto file to the appropriate path in the generated sources directory (as we do in Stratum), then use the `proto_library` rule. So, as it stands, requirement (c) is not great in the short term.

It seems like protobuf has a rule in 3.2.0 that could be used in the short term: https://github.com/google/protobuf/blob/v3.2.0/protobuf.bzl#L149

I haven't tried this yet, but I can try in the next few days.

**Comment by bocon13** [comment] 2018-07-26 23:34
In the longer term, I'd like to move to native rules for `proto_library`, `cc_proto_library` and something based on native rules for gRPC. This would make it easier to support multiple languages.

**Comment by antoninbas** [comment] 2018-07-27 18:58
The problem is that all the Bazel files in Protobuf 3.2.0 (whether it's BUILD files or protobuf.bzl) are not compliant with recent versions of Bazel (such as the one we use for Stratum).
For example, for protobuf.bzl:
```
ERROR: /home/antonin/Documents/p4lang/PI/proto/p4runtime/proto/BUILD:8:1: Traceback (most recent call last):
	File "/home/antonin/Documents/p4lang/PI/proto/p4runtime/proto/BUILD", line 8
		cc_proto_library(name = "p4types", deps = [], srcs = ..."])
	File "/home/antonin/.cache/bazel/_bazel_antonin/6af8fe00661db4e7432e035b48767a7b/external/com_google_protobuf/protobuf.bzl", line 229, in cc_proto_library
		cc_libs += [default_runtime]
trying to mutate a frozen object
```
For the BUILD file, this line is not correct and should read `:protobuf`: https://github.com/google/protobuf/blob/3.2.x/BUILD#L34

I think I'm just going to fork Protobuf 3.2.0 and patch the BUILD files if it's not too much work.

**Comment by antoninbas** [comment] 2018-08-14 18:59
Closing this for now as initial support was added. For improvements (support for other languages, use native rules instead of pubref rules, CI for rules), new issues can be opened.

**Closed by antoninbas** 2018-08-14 18:59 UTC
